server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9090
    - type: https
      port: 9091

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: info
